listen = '0.0.0.0:8443'
cert_file = 'fullchain.pem'
pkey_file = 'privkey.pem'
redirect_to_https = false

[[routes]]
source = '/'
target = '127.0.0.1:8000'
allowed_methods = []

[[routes]]
source = '/stuff'
target = '127.0.0.1:7000'
allowed_methods = [
    'GET',
    'POST',
]
